theme: jekyll-theme-minimal
title: Quote Of The Day 
description: Your only limit is your mind. Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle
